# Generated by Django 5.2.4 on 2025-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_rename_tickets_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='emailAddress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='modifiedAt',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='websiteName',
            new_name='website_name',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.TextField(),
        ),
    ]
